### ISSUE TITLE
"java.lang.ClassNotFoundException" error occurs when the player join the server.

### ISSUE THREAD

**Issue by KateLin-BASIC** [zDevelopers/zLib#83]
# Error Log
```
[17:51:43 WARN]: [Metrics] Unable to get the required classes to send scoreboard packets
java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.PacketPlayOutScoreboardObjective
        at java.lang.Class.forNameImpl(Native Method) ~[?:?]
        at java.lang.Class.forName(Unknown Source) ~[?:?]
        at xyz.katelin.metrics.Metrics.tools.reflection.Reflection.getMinecraftClassByName(Reflection.java:119) ~[metrics-1.0.0.jar:?]
        at xyz.katelin.metrics.Metrics.components.scoreboard.sender.ObjectiveSender.<clinit>(ObjectiveSender.java:95) ~[metrics-1.0.0.jar:?]
        at xyz.katelin.metrics.Metrics.components.scoreboard.OnlinePlayersListener.onPlayerJoin(OnlinePlayersListener.java:46) ~[metrics-1.0.0.jar:?]
        at java.lang.invoke.LambdaForm$DMH/0x00000000f0a77190.invokeVirtual(LambdaForm$DMH) ~[?:?]
        at java.lang.invoke.LambdaForm$MH/0x00000000949d36b0.invoke(LambdaForm$MH) ~[?:?]
        at java.lang.invoke.LambdaForm$MH/0x00000000966ab290.invoke_MT(LambdaForm$MH) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1503]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:359) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:301) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.players.PlayerList$$Lambda$6404/0x0000000099cbe548.run(Unknown Source) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:323) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:526) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1664) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1503]
        at net.minecraft.server.MinecraftServer$$Lambda$3978/0x0000000096860c70.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

# pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>xyz.katelin</groupId>
    <artifactId>metrics</artifactId>
    <version>1.0.0</version>
    <packaging>jar</packaging>

    <name>Metrics</name>

    <description>플레이어들의 게임 시간을 기록하고 통계로 보여줍니다.</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <url>https://katelin.xyz</url>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>10</source>
                    <target>10</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <configuration>
                    <artifactSet>
                        <includes>
                            <include>fr.zcraft:quartzlib</include>
                        </includes>
                    </artifactSet>
                    <relocations>
                        <relocation>
                            <pattern>fr.zcraft.quartzlib</pattern>
                            <shadedPattern>xyz.katelin.metrics.Metrics</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>QuartzLib</id>
            <url>https://maven.zcraft.fr/QuartzLib</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.bukkit</groupId>
            <artifactId>bukkit</artifactId>
            <version>1.13.2-R0.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>fr.zcraft</groupId>
            <artifactId>quartzlib</artifactId>
            <version>0.0.5</version>
        </dependency>
    </dependencies>
</project>
```

# plugin.yml
```yml
name: Metrics
version: '${project.version}'
main: xyz.katelin.metrics.Metrics
api-version: 1.13
prefix: Metrics
authors: [ KateLin4567 ]
description: 플레이어들의 게임 시간을 기록하고 통계로 보여줍니다.
website: https://katelin.xyz
```

# Server information
- Purpur Version: 1.18.1-1503 (also occurs in the lastest spigot version)
- Java Version: IBM Semeru Runtime Open Edition 17.0.1.0 (build 17.0.1+12)

**Comment by KateLin-BASIC** [comment]
**FIXED (for now):** Remove "SidebarScoreboard.class" from "loadComponents()", it works normally.
